'use strict';
const $=id=>document.getElementById(id),{Population,Research,stats}=SnailModel;
let seed=Date.now()>>>0,pop=new Population(seed),crabs=0,tool='select',running=false,timer=null,mode='main',research=null,researchTimer=null,selected=[],inspected=null;
const lessons={
 intro:{title:'A change on a real coast',text:'In the workbook’s Prelude, compare periwinkle shells collected in 1871 and 1982–1984. Robin Seeley asked whether predation by green crabs could explain the difference.',steps:['Plot the two real datasets in the workbook.','Compare each population’s mean and range.','Use the model to test a possible explanation.'],prompt:'A changed population is evidence to explain. What would you need to show that natural selection caused the change?'},
 main:{title:'Be the crab.',text:'The coast starts with 50 snails. Their shells vary in thickness. Which snails will leave offspring?',steps:['Use Select to inspect at least 10 snails. Save the starting histogram.','Choose Claw. Click snails until you have eaten 25. Fewer clicks earn a higher happiness score.','Let the 25 survivors reproduce. Repeat for three meals, ending at generation 4.','Reset, add 3–5 crabs and use Run to repeat the experiment.'],prompt:'Predict: how will the distribution change? Explain why using the snails that survive and reproduce.'},
 requirements:{title:'Remove one condition.',text:'Change one setting at a time. Save a starting and ending histogram for every experiment.',steps:['Variation: uncheck “Shell thickness is variable”, reset and complete one meal and reproduction.','Inheritance: restore variation, uncheck “Shell thickness is heritable”, reset and complete three meals and reproductions.','Selection: restore inheritance, uncheck “Survival is selective”, reset and use Eat random snail(s).','Repeat the no-selection trial three times. Compare their directions of change.'],prompt:'Does a changing population always mean natural selection? Distinguish a consistent advantage from chance.'},
 theory:{title:'Build an explanation.',text:'Use your results from Exercises 1 and 2 to explain when a population evolves toward thicker shells.',steps:['Identify variation among individuals.','Use parent–offspring evidence to discuss inheritance.','Describe which snails survived and left offspring.','Refer to your saved histograms.'],prompt:'Exercise 3, Q1.1: Under which conditions did thicker shells become more common? Under which conditions did they not?'},
 mutation:{title:'Where do new traits come from?',text:'This coast starts with thicknesses 1–4. Mutation is initially off. An individual’s shell thickness stays fixed throughout its life in this model.',steps:['Add 3–5 crabs. Complete three meals, reproducing between meals. Look for a limit.','Turn on “Reproduce with mutation”, then reproduce after the third meal.','Before predation, inspect offspring and open Parent–offspring evidence. Compare both directions of change.','Continue for at least five more meals and reproductions.'],prompt:'Mutation does not know what a snail needs. Are new variants produced only in the direction that helps survival?'},
 reflection:{title:'Individuals or populations?',text:'Return to your observations rather than relying only on the final average.',steps:['Did any individual change its thickness after birth?','Where did thicknesses absent from the starting population come from?','What did predators change: the traits being produced, or which snails survived to reproduce?'],prompt:'Write a complete explanation using variation, inheritance, survival and reproduction.'},
 research:{title:'You are the scientist.',text:'Read Exercise 6 in the workbook, then design a controlled experiment. West and East are model source populations with different histories.',steps:['Compare the two source samples. Select juveniles or adults and transfer them into four tanks.','Keep starting numbers, life stages and timing comparable. Change one factor.','Compare no crab, an active crab and a banded crab.','Track individuals and offspring. Save tank and individual data; repeat your experiment.'],prompt:'Can you separate inherited differences from shell growth caused by environmental cues? Your model results cannot prove what happened in wild populations.'}
};
function lesson(){const l=lessons[mode];$('lesson').innerHTML=`<h2>${l.title}</h2><p>${l.text}</p><ol>${l.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="prompt"><strong>THINK IT THROUGH</strong>${l.prompt}</div>`;}
function say(s){$('status').textContent=s;}
function filter(t){return `hue-rotate(${Math.max(-30,95-t*21)}deg) saturate(${.7+t*.12}) brightness(${1.25-Math.min(t,12)*.035})`;}
function table(headers,rows){return '<table><thead><tr>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>`<td>${v??'—'}</td>`).join('')+'</tr>').join('')+'</tbody></table>';}
function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
function downloadCanvas(canvas,name){canvas.toBlob(b=>{if(!b)return;const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);});}
function histogram(){const c=$('histogram'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);const maxT=Math.max(7,...pop.snails.map(s=>s.t)),bins=Array.from({length:maxT},(_,i)=>pop.snails.filter(s=>s.t===i+1).length),yMax=Math.max(5,...bins),left=43,right=16,top=40,bottom=40,bw=(w-left-right)/bins.length;
 ctx.font='16px system-ui';ctx.fillStyle='#17383e';ctx.fillText(`Generation ${pop.gen} · n = ${pop.snails.length} · mean = ${stats(pop.snails).mean.toFixed(2)}`,left,21);for(let i=0;i<=4;i++){const y=h-bottom-(h-top-bottom)*i/4;ctx.strokeStyle='#e4ecee';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-right,y);ctx.stroke();ctx.fillStyle='#5e747a';ctx.font='12px system-ui';ctx.fillText(String(Math.round(yMax*i/4)),10,y+4);}bins.forEach((n,i)=>{const bh=n/yMax*(h-top-bottom);ctx.fillStyle=`hsl(${Math.max(15,65-i*8)},68%,${55-i*2}%)`;ctx.fillRect(left+i*bw+3,h-bottom-bh,bw-6,bh);ctx.fillStyle='#17383e';ctx.textAlign='center';ctx.font='14px system-ui';ctx.fillText(i+1,left+(i+.5)*bw,h-bottom+19);if(n)ctx.fillText(n,left+(i+.5)*bw,h-bottom-bh-5);});ctx.textAlign='left';ctx.fillStyle='#5e747a';ctx.font='12px system-ui';ctx.fillText('Shell thickness (model units)',left,h-3);$('histTable').innerHTML=table(['Thickness','Number alive'],bins.map((n,i)=>[i+1,n]));c.setAttribute('aria-label',`Shell thickness counts: ${bins.map((n,i)=>`${i+1}: ${n}`).join('; ')}`);}
function trend(){const c=$('trend'),ctx=c.getContext('2d'),w=c.width,h=c.height,left=44,top=40,bottom=40;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);let data=pop.history.filter(d=>d.phase!=='survivors before reproduction');const max=Math.max(7,...data.map(d=>d.mean))+1;ctx.font='16px system-ui';ctx.fillStyle='#17383e';ctx.fillText('Mean thickness at the start of each generation',left,21);for(let i=0;i<=4;i++){const y=h-bottom-(h-top-bottom)*i/4;ctx.strokeStyle='#e4ecee';ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-20,y);ctx.stroke();ctx.fillStyle='#5e747a';ctx.font='12px system-ui';ctx.fillText((max*i/4).toFixed(1),8,y+4);}const xy=d=>[left+(d.generation-1)/Math.max(3,pop.gen-1)*(w-left-22),h-bottom-d.mean/max*(h-top-bottom)];ctx.strokeStyle='#087e8b';ctx.lineWidth=3;ctx.beginPath();data.forEach((d,i)=>{const [x,y]=xy(d);if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);});ctx.stroke();data.forEach(d=>{const [x,y]=xy(d);ctx.fillStyle='#087e8b';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();if(data.length<15||d.generation%5===0){ctx.fillStyle='#5e747a';ctx.fillText(d.generation,x-4,h-bottom+19);}});ctx.fillText('Generation',left,h-3);c.setAttribute('aria-label','Mean thickness at birth: '+data.map(d=>`generation ${d.generation}, ${d.mean.toFixed(2)}`).join('; '));}
function renderSnails(){const focus=document.activeElement?.dataset.snail;$('snails').replaceChildren();for(const s of pop.snails){const b=document.createElement('button');b.className='snail';b.dataset.snail=s.id;b.style.left=s.x*100+'%';b.style.top=s.y*100+'%';b.style.setProperty('--filter',filter(s.t));b.setAttribute('aria-label',`Snail ${s.id}, shell thickness ${s.t}${s.hits?', '+s.hits+' claw hits':''}`);b.innerHTML=`<img src="assets/snail.png" alt="" draggable="false"><span class="snail-badge">${s.t}</span>`;b.onclick=()=>snailClick(s.id);$('snails').append(b);}if(focus)$('snails').querySelector(`[data-snail="${focus}"]`)?.focus({preventScroll:true});}
function renderBirths(){const up=pop.mutations.filter(b=>b.delta>0).length,down=pop.mutations.filter(b=>b.delta<0).length;$('mutationSummary').textContent=pop.settings.mutation?`· ${up} thicker / ${down} thinner (all births)`:'';$('birthTable').innerHTML=pop.births.length?table(['Offspring ID','Parent ID','Parent thickness','Offspring thickness','Change'],pop.births.map(b=>[b.id,b.parent,b.parentT,b.offspringT,b.delta>0?'+'+b.delta:b.delta])):'<p>No offspring yet. Reproduce to collect parent–offspring evidence.</p>';}
function render(){const st=stats(pop.snails);$('generation').textContent=pop.gen;$('count').textContent=st.n;$('mean').textContent=st.mean.toFixed(2);$('score').textContent=pop.score;$('crabCount').textContent=crabs+' crab'+(crabs===1?'':'s');$('crabs').innerHTML=Array.from({length:crabs},(_,i)=>`<span class="crab-icon" style="left:${8+i*16}%">🦀</span>`).join('');$('runState').textContent=running?'Running':'Paused';$('randomControls').hidden=pop.settings.selective;$('mutationLabel').hidden=mode!=='mutation';$('variable').checked=pop.settings.variable;$('heritable').checked=pop.settings.heritable;$('selective').checked=pop.settings.selective;$('mutation').checked=pop.settings.mutation;renderSnails();histogram();trend();renderBirths();}
function stop(){running=false;clearInterval(timer);timer=null;$('runState').textContent='Paused';$('run').disabled=false;}
function start(){stop();running=true;$('runState').textContent='Running';$('run').disabled=true;timer=setInterval(()=>{if(crabs&&pop.snails.length>25){pop.eat(Math.min(crabs,pop.snails.length-25));render();if(pop.snails.length===25){stop();say('25 survivors remain. Save your histogram, then let the snails reproduce.');}}else if(crabs&&pop.snails.length<=25){stop();say('Predation pauses at 25 survivors. Let the snails reproduce.');}if(!matchMedia('(prefers-reduced-motion: reduce)').matches){for(const s of pop.snails){s.x=Math.max(.04,Math.min(.96,s.x+(Math.random()-.5)*.015));s.y=Math.max(.12,Math.min(.92,s.y+(Math.random()-.5)*.02));const b=$('snails').querySelector(`[data-snail="${s.id}"]`);if(b){b.style.left=s.x*100+'%';b.style.top=s.y*100+'%';}}}},Number($('speed').value));say(crabs?'Crabs are feeding. Predation will pause at 25 survivors.':'Snails are moving. Select Claw or add crabs to feed.');}
function snailClick(id){if(tool==='select'){inspect(id);return;}if(pop.snails.length<=25){say('Meal complete: 25 survivors. Reproduce before eating another meal.');return;}const eaten=pop.claw(id),s=pop.snails.find(s=>s.id===id);render();say(eaten?`Snail eaten. ${pop.snails.length} remain.`:`Shell resists: ${s.hits} of ${Math.ceil(s.t)} clicks.`);if(pop.snails.length===25){stop();say('Meal complete. Save the survivors’ histogram, then click Snails reproduce.');}}
function inspect(id){const s=pop.snails.find(s=>s.id===id);if(!s)return;stop();inspected=id;$('snailName').textContent=`Snail ${s.id}`;$('snailDetails').innerHTML=`<p><b>Shell thickness: ${s.t}</b> model units</p><p>${s.parent===null?'Part of the starting population.':`Parent: snail ${s.parent} · parent thickness ${s.parentT}<br>Sibling group: ${s.pair}`}</p><p>${s.mutated?'This offspring has a mutation that changed shell thickness.':'Thickness remains fixed after birth in this model.'}</p>`;if(!$('inspector').open)$('inspector').showModal();}
function reset(){stop();seed=(seed+1)>>>0;pop=new Population(seed,{...pop.settings});crabs=0;render();say('New trial started. Previous graphs are cleared; your written notes are retained.');}
$('run').onclick=start;$('stop').onclick=()=>{stop();say('Paused. Inspect snails or save your evidence.');};$('speed').onchange=()=>{if(running)start();};$('reproduce').onclick=()=>{stop();const r=pop.reproduce();render();say(r.error||`Generation ${pop.gen}: ${pop.snails.length} offspring. Inspect siblings before the next meal.`);};$('reset').onclick=reset;
$('selectTool').onclick=()=>{tool='select';$('selectTool').setAttribute('aria-pressed','true');$('clawTool').setAttribute('aria-pressed','false');say('Select a snail to inspect it.');};$('clawTool').onclick=()=>{tool='claw';$('selectTool').setAttribute('aria-pressed','false');$('clawTool').setAttribute('aria-pressed','true');say('Click a snail repeatedly to crack its shell. Thicker shells take more clicks.');};$('addCrab').onclick=()=>{if(crabs<5)crabs++;render();say('Crab added. Click Run to start feeding.');};$('clearCrabs').onclick=()=>{crabs=0;render();say('Crabs removed.');};$('zoom').onchange=()=>$('habitat').classList.toggle('zoom',$('zoom').checked);
for(const key of ['variable','heritable','selective','mutation'])$(key).onchange=()=>{stop();pop.settings[key]=$(key).checked;render();say(key==='variable'?'Starting variation changed. Click Reset trial to apply it.':key==='mutation'?'Mutation setting changed. It takes effect at the next reproduction.':'Setting changed. Reset trial before a new comparison.');};
$('randomEat').onclick=()=>{stop();const n=Math.min(Number($('randomN').value),Math.max(0,pop.snails.length-25));pop.eat(n,false);render();say(n?`${n} snail(s) removed at random, independently of thickness.`:'25 survivors remain. Reproduce to start the next meal.');};
$('saveGraph').onclick=()=>downloadCanvas($('histogram'),`snails-${mode}-generation-${pop.gen}-n${pop.snails.length}.png`);
$('exportCSV').onclick=()=>{const rows=[['seed','generation','phase','n','mean','min','max','variable','heritable','selective','mutation','thicknesses']];[...pop.history,{generation:pop.gen,phase:'current population',...stats(pop.snails),settings:{...pop.settings},distribution:pop.snails.map(s=>s.t)}].forEach(d=>rows.push([seed,d.generation,d.phase,d.n,d.mean,d.min,d.max,d.settings.variable,d.settings.heritable,d.settings.selective,d.settings.mutation,d.distribution.join(';')]));download('snail-population-data.csv',csv(rows),'text/csv');};
$('exportBirths').onclick=()=>download('mutation-events.csv',csv([['generation','offspring_id','parent_id','parent_thickness','offspring_thickness','actual_change','attempted_change'],...pop.mutations.map(b=>[b.generation,b.id,b.parent,b.parentT,b.offspringT,b.delta,b.attempt])]),'text/csv');
$('closeInspector').onclick=()=>$('inspector').close();$('inspectNext').onclick=()=>{const i=pop.snails.findIndex(s=>s.id===inspected);inspect(pop.snails[(i+1)%pop.snails.length]?.id);};$('helpBtn').onclick=()=>$('help').showModal();$('closeHelp').onclick=()=>$('help').close();
$('exercise').onchange=()=>{stop();stopResearch();const before=mode;mode=$('exercise').value;$('mainLab').hidden=mode==='research';$('researchLab').hidden=mode!=='research';if(mode==='research'){if(!research)research=new Research(seed+100);renderResearch();}else if((mode==='mutation')!==(before==='mutation')||mode==='main'||mode==='requirements'){pop=new Population(++seed,{mode:mode==='mutation'?'mutation':'main'});crabs=0;render();say('A new starting population is ready. Save evidence before changing investigations.');}else render();lesson();};

function stopResearch(){clearInterval(researchTimer);researchTimer=null;$('researchRun').disabled=false;}
function researchSnail(s,origin){const chosen=selected.some(x=>x.origin===origin&&x.id===s.id);return `<button class="research-snail ${s.age<3?'juvenile':''}" aria-pressed="${chosen}" data-origin="${origin}" data-id="${s.id}" aria-label="Select snail ${s.id}, thickness ${s.t.toFixed(2)}, ${s.age<3?'juvenile':'adult'}" style="--filter:${filter(s.t)}"><img src="assets/snail.png" alt=""><span>${s.id}</span></button>`;}
function miniHistogram(snails){const bins=Array.from({length:10},(_,i)=>snails.filter(s=>i===9?s.t>=9:Math.floor(s.t)===i).length),max=Math.max(1,...bins);return `<div class="research-bar" role="img" aria-label="Thickness bins ${bins.map((n,i)=>i+': '+n).join(', ')}">${bins.map((n,i)=>`<i title="Thickness ${i}–${i+1}: ${n}" style="height:${n/max*100}%"></i>`).join('')}</div><div class="mini-stats">Thickness bins: 0 (left) → 9+ (right)</div>`;}
function box(snails,title,origin,controls=''){const s=stats(snails);return `<section class="population-box"><h2>${title}</h2><div class="mini-stats">${s.n} snails · mean ${s.mean.toFixed(2)} · range ${s.min.toFixed(1)}–${s.max.toFixed(1)}</div><div class="small-habitat">${snails.length?snails.map(s=>researchSnail(s,origin)).join(''):'<span class="research-empty">Transfer snails here to begin.</span>'}</div>${miniHistogram(snails)}${controls}</section>`;}
function renderResearch(){if(!research)return;$('day').textContent='Day '+research.day;$('coasts').innerHTML=['west','east'].map(o=>box(research.coasts[o],o==='west'?'West · crab-free history':'East · crab-exposed history',o,`<div class="small-controls"><button data-sample="${o}:juvenile">Select 10 juveniles</button><button data-sample="${o}:adult">Select 10 adults</button></div>`)).join('');$('tanks').innerHTML=research.tanks.map((t,i)=>box(t.snails,t.name,'tank'+i,`<label>Crab treatment <select data-tank="${i}"><option value="none" ${t.crab==='none'?'selected':''}>No crab</option><option value="active" ${t.crab==='active'?'selected':''}>Active crab</option><option value="banded" ${t.crab==='banded'?'selected':''}>Banded crab · cues only</option></select></label><div class="small-controls"><button data-tankselect="${i}">Select all snails</button></div>`)).join('');
 document.querySelectorAll('.research-snail').forEach(b=>b.onclick=()=>{stopResearch();const item={origin:b.dataset.origin,id:Number(b.dataset.id)},i=selected.findIndex(s=>s.origin===item.origin&&s.id===item.id);if(i>=0)selected.splice(i,1);else selected.push(item);renderResearch();});document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=()=>{const[o,stage]=b.dataset.sample.split(':');selected=research.coasts[o].filter(s=>stage==='juvenile'?s.age<3:s.age>=3).slice(0,10).map(s=>({origin:o,id:s.id}));renderResearch();});document.querySelectorAll('[data-tankselect]').forEach(b=>b.onclick=()=>{const i=+b.dataset.tankselect;selected=research.tanks[i].snails.map(s=>({origin:'tank'+i,id:s.id}));renderResearch();});document.querySelectorAll('[data-tank]').forEach(b=>b.onchange=()=>{stopResearch();research.tanks[+b.dataset.tank].crab=b.value;research.record();$('researchStatus').textContent='Treatment changed. It will apply when you advance time.';});
 const details=selected.map(x=>{const s=(x.origin.startsWith('tank')?research.tanks[+x.origin.slice(4)].snails:research.coasts[x.origin]).find(s=>s.id===x.id);return s?`#${s.id}: ${s.t.toFixed(2)}, ${s.age<3?'juvenile':'adult'}, born ${s.atBirth.toFixed(2)}`:null;}).filter(Boolean);$('selectionDetails').textContent=details.length?`${details.length} selected. `+details.join(' · '):'No snails selected.';$('researchIndividuals').innerHTML=table(['Tank','ID','Origin','Stage','Age','Thickness at birth','Current thickness','Parents'],research.tanks.flatMap(t=>t.snails.map(s=>[t.name,s.id,s.origin,s.age<3?'juvenile':'adult',s.age,s.atBirth.toFixed(2),s.t.toFixed(2),s.parents.join(' + ')||'source sample'])));}
$('transfer').onclick=()=>{stopResearch();const dest=+$('destination').value;for(const origin of [...new Set(selected.map(s=>s.origin))])research.transfer(origin.startsWith('tank')?+origin.slice(4):origin,dest,selected.filter(s=>s.origin===origin).map(s=>s.id));selected=[];renderResearch();$('researchStatus').textContent='Selected snails moved. Choose crab treatments and advance time.';};$('clearSelection').onclick=()=>{selected=[];renderResearch();};
function researchStep(){research.step();selected=[];renderResearch();$('researchStatus').textContent=`Day ${research.day}. Juveniles mature at age 3; adult pairs may reproduce every 3 days. Review living individuals and save your observations.`;}
$('researchStep').onclick=()=>{stopResearch();researchStep();};$('researchRun').onclick=()=>{stopResearch();$('researchRun').disabled=true;researchTimer=setInterval(()=>{researchStep();if(research.day%15===0){stopResearch();$('researchStatus').textContent+=' Auto-run paused for observations.';}},1500);};$('researchStop').onclick=stopResearch;$('researchReset').onclick=()=>{stopResearch();research=new Research(++seed);selected=[];renderResearch();$('researchStatus').textContent='Research reset. Save CSV data before resetting a completed trial.';};
$('researchSave').onclick=()=>download('research-tank-data.csv',csv([['day','tank','treatment','n','mean_thickness','min','max','juveniles'],...research.records.map(r=>[r.day,r.tank,r.crab,r.n,r.mean,r.min,r.max,r.juveniles])]),'text/csv');
$('researchIndividualsSave').onclick=()=>download('research-individuals.csv',csv([['day','tank','id','origin','age','birth_thickness','current_thickness','parent_ids','event'],...research.tanks.flatMap(t=>t.snails.map(s=>[research.day,t.name,s.id,s.origin,s.age,s.atBirth,s.t,s.parents.join(';'),'alive'])),...research.events.map(e=>[e.day,e.tank,e.id,'','', '',e.t,'',e.event])]),'text/csv');
try{$('notes').value=localStorage.getItem('snails-notes-v1')||'';}catch(e){$('notesStatus').textContent='Browser storage is unavailable. Download your notes before leaving.';}$('notes').oninput=()=>{try{localStorage.setItem('snails-notes-v1',$('notes').value);}catch(e){$('notesStatus').textContent='Notes could not be saved in this browser. Download a copy.';}};$('downloadNotes').onclick=()=>download('snail-lab-notes.txt',$('notes').value);lesson();render();
// Optional browser agent integration; ordinary browsers need no polyfill.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({
  name:'read_snail_lab_measurements',title:'Read current snail measurements',
  description:'Read the population measurements currently available in the snail lab. Does not advance, reset, or modify the experiment.',
  inputSchema:{type:'object',properties:{},additionalProperties:false},
  annotations:{readOnlyHint:true,untrustedContentHint:false},
  execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object.');if(mode==='research')return{exercise:mode,day:research.day,tanks:research.tanks.map(t=>({name:t.name,treatment:t.crab,...stats(t.snails)}))};return{exercise:mode,generation:pop.gen,settings:{...pop.settings},...stats(pop.snails),counts:pop.snails.reduce((m,s)=>(m[s.t]=(m[s.t]||0)+1,m),{})};}
 },{signal:lifecycle.signal})).catch(()=>{});}catch(e){}
 addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
